[build] # Make sure you don't have a duplicate [build] context!
  functions = "functions/"
  publish = "build/"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "/.netflify/functions/:splat"